services:
  # PostgreSQL Database
  - type: pserv
    name: reengage-postgres
    env: docker
    plan: free
    dockerfilePath: ./dittofeed/packages/postgres/Dockerfile
    dockerContext: ./dittofeed
    envVars:
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_DB
        value: dittofeed

  # ClickHouse Database
  - type: pserv
    name: reengage-clickhouse
    env: docker
    plan: starter
    dockerfilePath: ./dittofeed/Dockerfile.clickhouse
    dockerContext: ./dittofeed
    disk:
      name: clickhouse-data
      mountPath: /var/lib/clickhouse
      sizeGB: 10
    envVars:
      - key: CLICKHOUSE_USER
        value: dittofeed
      - key: CLICKHOUSE_PASSWORD
        generateValue: true

  # Dittofeed Lite Service
  - type: web
    name: reengage-app
    env: docker
    plan: starter
    dockerfilePath: ./dittofeed/packages/lite/Dockerfile
    dockerContext: ./dittofeed
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: reengage-postgres
          property: connectionString
      - key: CLICKHOUSE_HOST
        fromService:
          type: pserv
          name: reengage-clickhouse
          property: host
      - key: CLICKHOUSE_USER
        value: dittofeed
      - key: CLICKHOUSE_PASSWORD
        fromService:
          type: pserv
          name: reengage-clickhouse
          envVarKey: CLICKHOUSE_PASSWORD
      - key: PASSWORD
        value: ReEngage2024!
      - key: WORKSPACE_NAME
        value: ReEngage
      - key: SECRET_KEY
        generateValue: true
      - key: NODE_ENV
        value: production
